from PIL import Image
img1 = Image.open("Obrazok.png")
img1 = img1.resize((700,500))
img = Image.new("RGB",(1400,500),(250,250,250))
img.paste(img1,(0,0))
pix1 = img1.load()
#for i in range(img1.size[0]):
    #for j in range(img1.size[1]):
        #sf = int(sum(pix1[i,j])/3)
        #pix1[i,j] = (sf,sf,sf)
for y in range(0,img1.size[1]-1):
    for x in range(1,img1.size[0]-1):
        oldred = int(pix1[x,y][0])
        oldgreen = int(pix1[x,y][1])
        oldblue = int(pix1[x,y][2])    
        newred = round(oldred/255)*(255)
        newgreen = round(oldgreen/255)*(255)
        newblue = round(oldblue/255)*(255)
        pix1[x,y] = (newred,newgreen,newblue)
        errR = float(oldred - newred)
        errG = float(oldgreen - newgreen)
        errB = float(oldblue - newblue)
        c = (pix1[x+1,y])
        r = float(c[0])
        g = float(c[1])
        b = float(c[2])
        r = int(r + errR * 7/16.0)
        g = int(g + errR * 7/16.0)
        b = int(b + errB * 7/16.0)
        pix1[x+1,y] = (r,g,b)
        c = (pix1[x-1,y+1])
        r = float(c[0])
        g = float(c[1])
        b = float(c[2])
        r = int(r + errR * 3/16.0)
        g = int(g + errR * 3/16.0)
        b = int(b + errB * 3/16.0)
        pix1[x-1,y+1] = (r,g,b)

        c = (pix1[x,y+1])
        r = float(c[0])
        g = float(c[1])
        b = float(c[2])
        r = int(r + errR * 5/16.0)
        g = int(g + errR * 5/16.0)
        b = int(b + errB * 5/16.0)
        pix1[x,y+1] = (r,g,b)

        c = (pix1[x+1,y+1])
        r = float(c[0])
        g = float(c[1])
        b = float(c[2])
        r = int(r + errR * 1/16.0)
        g = int(g + errR * 1/16.0)
        b = int(b + errB * 1/16.0)
        pix1[x+1,y+1] = (r,g,b)
img.paste(img1,(700,0))
img.show()
#img.paste(img2,(700,0))
#img.show()



